!!python/object:nuplan_scripts.utils.config.RoadBlockConfig
city: sg-one-north
data_root: ./data/MTGS
interval: 1
reconstruct_buffer: 0
expand_buffer: 0
exclude_bad_registration: false
use_colmap_ba: false
collect_raw: true
road_block: !!python/tuple
- 365530
- 143960
- 365630
- 144060
road_block_name: road_block-365530_143960_365630_144060
selected_videos: !!python/tuple
- 1
- 2
- 5
- 6