!!python/object:nuplan_scripts.utils.config.RoadBlockConfig
city: us-ma-boston
data_root: ./data/MTGS
interval: 1
reconstruct_buffer: 0
expand_buffer: 0
exclude_bad_registration: false
use_colmap_ba: false
collect_raw: true
road_block: !!python/tuple
- 331120
- 4690660
- 331190
- 4690710
road_block_name: road_block-331220_4690660_331190_4690710
selected_videos: !!python/tuple
- 0
- 1
- 2
- 6
- 7
- 8
